### ISSUE TITLE
connection to TorProject every 10 mins

### ISSUE THREAD

**Issue by Sp-TT** [intelowlproject/IntelOwl#1133]
## What happened
I can see IntelOwl sending request to [https://check.torproject.org/] every 10 mins in my environment. I disabled TorProject in analyzer config file and can still see this traffic.

Wondering is this a heartbeat traffic from IntelOwl? If it is, is there a way to disable it?

**Comment by 0ssigeno** [comment]
Hi!
There is a [celery cron](https://github.com/intelowlproject/IntelOwl/blob/8d5620c183a0e30c5a00bca0824ad12d8989f90b/intel_owl/celery.py#L87) that is executed inside celery every 10 minutes. Unfortunately, it does not check at the moment that its own analyzer is enabled.
Since i can see why this is misleading, I will add this check, I will tag this Issue on the PR

**Comment by mlodic** [comment]
We fixed that. All those updaters won't work if you have disabled the related analyzer. Available from the next release.
