### ISSUE TITLE
Problem with jobs and dashboard

### ISSUE THREAD

**Issue by LumberJohn6** [intelowlproject/IntelOwl#1171]
## What happened
Jobs and data from the dashboard disappear. Don't know if its a database problem or anything else really.

## Environment
1. OS: Ubuntu 22.04
2. IntelOwl version: v4.0.1

##  What did you expect to happen
Dashboard populated with info from the executed scans and jobs list also populated with information on jobs. Instead, they are empty.

## How to reproduce your issue
Fresh installation of IntelOwl, configure plugins and HTTPS, then run jobs. Sometimes they don't register on jobs list or dashboard, other times they register but the day after they are gone.

## Error messages and logs
>2022/08/29 15:17:59 [warn] 34#34: *29 an upstream response is buffered to a temporary file /var/cache/nginx/uwsgi_temp/1/00/0000000001 while reading upstream, client: <IP>, server: intelowl.cert.rcts.pt, request: "GET /api/get_analyzer_configs HTTP/1.1", upstream: "uwsgi://172.18.0.4:8001", host: "intelowl.cert.rcts.pt", referrer: "https://intelowl.cert.rcts.pt/jobs?ordering=-received_request_time"
2022/08/29 15:18:03 [warn] 31#31: *23 an upstream response is buffered to a temporary file /var/cache/nginx/uwsgi_temp/2/00/0000000002 while reading upstream, client: <IP>, server: intelowl.cert.rcts.pt, request: "GET /api/get_analyzer_configs HTTP/1.1", upstream: "uwsgi://172.18.0.4:8001", host: "intelowl.cert.rcts.pt", referrer: "https://intelowl.cert.rcts.pt/dashboard"

**Comment by mlodic** [comment]
hey!

First things that come to my mind:

![image](https://user-images.githubusercontent.com/30625432/187237610-7bf41bad-5d5c-47c8-812b-92a68de2dd53.png)

to update the data in that view you need to client the specific button at the top right. Otherwise that is not done by default for performance reasons.

Plus, Jobs are automatically deleted after X days. Default is 3 but you can change it. There is a specific env variable you need to set for this (OLD_JOBS_RETENTION_DAYS). This is written in the docs: https://intelowl.readthedocs.io/en/latest/Installation.html

**Comment by LumberJohn6** [comment]
Thank you for the quick response!
I didn't know that the jobs are automatically deleted, which can be the cause of my "problem".
I'll run some jobs today and see if tomorrow they are still on the jobs list or deleted and then update this issue.

**Comment by mlodic** [comment]
I close this. If there is any update, feel free to reopen it
