### ISSUE TITLE
Add Pulsedive Analyzer

### ISSUE THREAD

**Issue by netbroom** [intelowlproject/IntelOwl#137]
API documentation: https://pulsedive.com/api/

About Pulsedive: https://pulsedive.com/about/

IOC example and URL formats:
By raw value: https://pulsedive.com/indicator/?indicator=github.com
By Base64-encoded IOC: https://pulsedive.com/indicator/?ioc=Z2l0aHViLmNvbQ==
By IID: https://pulsedive.com/indicator/?iid=257710

API example:
https://pulsedive.com/api/?pretty=true&indicator=github.com

It sounds like it would be a nice addition as you can pull a ton of information back with one request, and if we don't have the IOC you can do an on-demand scan. There is a free API tier at 30 requests/minute.

If you have any questions or feedback please let me know! You can contact us at support@pulsedive.com.

**Comment by mlodic** [comment]
Thank you very much for your interest! We are going to add this soon. We will comment with updates.

**Comment by Eshaan7** [comment]
I was reading the documentation and I think for our case, we would want to integrate the [`/api/analyze.php`](https://pulsedive.com/api/#scan) endpoint for IP, domain and IOC (new) observable classifications. I couldn't find but does it support any other types of indicator as well, @netbroom ?

The `/api/analyze.php` is more fit than `/api/info.php` for Intel Owl users because the latter only works for existing indicators but the former returns immediately for the indicators already present in pulsedive's database, otherwise the requested observable is scanned (passive or active) and the result is available after a few seconds. Both from the same endpoint. This way the user would always get some data back from the API.

**Comment by netbroom** [comment]
Hey just saw this. The `analyze.php` will perform a scan regardless, so we recommend you send a query to `info.php` to check if the indicator is already in the database, and if you get an `error` key in the result object then run the scan with `analyze.php`.

The result object from `info.php` and `analyze.php` should be the same so if there are discrepancies please let me know.

We support URLs, IPs, IPv6s, and domains for scanning. Our file sample support is pretty lacking but more advanced static file analysis is in the roadmap.

If you have general feedback or suggestions feel free to reach out, the contact form on the website goes directly to myself and my cofounder, as does support@pulsedive.com. We have a Slack channel as well. I'll be checking back here in case you have follow-up questions for this issue.

**Comment by Eshaan7** [comment]
@netbroom We have integrated Pulsedive (PR #154) and it will be available to the users in the next release in a few days. We'd appreciate if you could list IntelOwl in the "Integrations" section on https://pulsedive.com/api/#libraries.
