### ISSUE TITLE
[Frontend] Observable is not copy-pastable

### ISSUE THREAD

**Issue by mlodic** [intelowlproject/IntelOwl#1404]
![image](https://user-images.githubusercontent.com/30625432/211284132-b81b255b-4bdf-41f6-a46e-215cf849588a.png)

In the Job Result page the observable name is not copy-pastable. We whould either make it copyable or add it a button for copy like the ones used in the Job List Page here:
![image](https://user-images.githubusercontent.com/30625432/211284440-f79430cb-d3ce-4c00-a7e7-ce360eb97d36.png)

**Comment by 0xquark** [comment]
Hi @mlodic 
I've been working on resolving the issue and I've managed to add the clipboard prop to the jobresult.jsx file. I'm still a bit new to React so I'm not exactly sure how we're supposed to get the IP/URL from the API. I need this in order to use it as a parameter for the copy function. Can you please clarify this for me?

**Comment by mlodic** [comment]
hey please move these kind of technical discussion into a draft open PR. Without code it is difficult to help

**Comment by tinaoberoi** [comment]
Hi @mlodic @0xquark is anyone working on this? If not I would like to take this up.

**Comment by 0xquark** [comment]
@mlodic @tinaoberoi  Sorry about that, I don't have much experience with React so I'm running into some issues. I think it would be best if you took a look at this while I work on other issues. Thanks!

**Comment by tinaoberoi** [comment]
@mlodic I would like to take this up if possible.

**Comment by manojku1803** [comment]
Hello @mlodic, I want to work in this.

**Comment by manojku1803** [comment]
@mlodic in this your frontend folder isn't working. It shows me this.
<img width="309" alt="image" src="https://user-images.githubusercontent.com/89033216/216250157-c32b118e-0d1f-4007-8b3a-4d4f3c54eb84.png">

**Comment by abodaa198911** [comment]
تم



لحصول عل BlueMail for Android



في يوم ٢ شباط ٢٠٢٣ ٩:٣٧ ص، الساعة ٩:٣٧ ص، كتب Manoj Kumar Pradhan ***@***.***>:

**Comment by msaini0r** [comment]
@mlodic I am trying to work on this issue. The problem here is that the button is already avaliable to copy on MD5. but it is hidden behind the next table column. I tried to modify the css in browser and it worked but I cannot locate the css file in the repository. Can you guide me where should I exactly look.

# Modified css in browser
![screen](https://user-images.githubusercontent.com/87536360/218530802-0278659a-b589-411b-b1c0-52f37140e61b.png)

**Comment by mlodic** [comment]
hey, please first read contribution guidelines and try to understand how the technology works...

**Comment by abheektripathy** [comment]
would like to take this up.

**Comment by mlodic** [comment]
solved in v4.2.2
