### ISSUE TITLE
Change defaults for LDAP configuration to Active Directory attribtues

### ISSUE THREAD

**Issue by yarpX** [intelowlproject/IntelOwl#1433]
## Environment
1. OS: Ubuntu 20.04
2. IntelOwl version: 4.1.5

##  What did you expect to happen
LDAP searches default to searching on uid, however most AD environments use sAMAccountName. I think, for ease of standup and configuration, the LDAP search values should be aligned to Active Directory. It's not the only LDAP provider, but it is by far the most prevalent.

## How to reproduce your issue
Try and authenticate with AD via LDAP without the uid attribute being filled on a user.

## Error messages and logs
2023-01-17 15:53:40,485 - django_auth_ldap - _process_results - DEBUG - search_s('OU=Users,DC=DOMAIN,DC=com', 2, '(uid=%(user)s)') returned 0 objects:

**Comment by yarpX** [comment]
Easiest fix: change configuration/ldap_config.py from:
```
AUTH_LDAP_USER_SEARCH = LDAPSearch(
    "ou=users,dc=example,dc=com",
    ldap.SCOPE_SUBTREE,
    "(uid=%(user)s)",
)
```

to

```
AUTH_LDAP_USER_SEARCH = LDAPSearch(
    "ou=users,dc=example,dc=com",
    ldap.SCOPE_SUBTREE,
    "(sAMAccountName=%(user)s)",
)
```

**Comment by mlodic** [comment]
hey thanks for reporting your issue. 

Consider that this is not a real bug because it is intended that the user needs to explore the LDAP python library and create his own ldap_config.py based on his personal configuration. See official docs: https://intelowl.readthedocs.io/en/latest/Advanced-Usage.html#ldap

What we can do is just to provide a comment with your suggested change so people in the same situation as yours can find the hint and solve the problem faster.

**Comment by yarpX** [comment]
Yeah, that makes sense. I had trouble changing the 'bug' tag. I really just wanted to make it easier for the next person, because I fought it for a while. Thanks!

**Comment by mlodic** [comment]
sure, that makes sense. I have already made a change, as you can see here: https://github.com/intelowlproject/IntelOwl/commit/0a2d5bf7fce1a3cecd40b023c2810b722062cbdb
