### ISSUE TITLE
[Frontend] guided tour/tutorial on first visit

### ISSUE THREAD

**Issue by mlodic** [intelowlproject/IntelOwl#1589]
Could be done something with this: https://github.com/gilbarbara/react-joyride

**Comment by abheektripathy** [comment]
hey @mlodic the flow should look like this, lemme know if there's something i missed.
we could have guide button on the header for whenever the user wants to display the guide.

<img width="512" alt="Screenshot 2023-08-22 at 3 37 34 PM" src="https://github.com/intelowlproject/IntelOwl/assets/90976669/16bf80c9-4495-4fd1-93f3-d0c9f48fd255">

**Comment by mlodic** [comment]
> we could have guide button on the header for whenever the user wants to display the guide.

This makes sense (like a "toggle" to enable/disable the tour).

Then, the tour you proposed makes completely sense at a first glance!

**Comment by mlodic** [comment]
The only that bothers me is that this tour should not always appear.
We should disable it once either the users have seen it completely or they have dismissed it.
The next time those users would log in, they should not see it.

Maybe a new boolean field in the User model could be used to keep track of this information. I understand that this could complicate things a bit so if you find a better solution of this problem it is welcome

**Comment by abheektripathy** [comment]
for simplicity, we could, instead of automatically starting the tour on login, have it toggled by 
the link on the header, something like this.
So i could handle everything in the frontend only, plus whenever the user would want they can start the tour by the toggle of that button, so it wouldn't be a bad UX choice as well, i think.

<img width="1279" alt="Screenshot 2023-08-22 at 4 34 40 PM" src="https://github.com/intelowlproject/IntelOwl/assets/90976669/907f4d33-acbb-4a0c-8bf7-b2860f535154">

**Comment by mlodic** [comment]
It makes sense. Just one thing I would change. I would move the "Guide" button next to the "Docs" button and use a new icon. Thank you!

**Comment by abheektripathy** [comment]
perfect, would do that.
