### ISSUE TITLE
Is it possible to get the results of a scan visable either in the internal dashboard or external like kibana + elasticsearch?

### ISSUE THREAD

**Issue by mrrobotnl** [intelowlproject/IntelOwl#1671]
**Question:**
Is it perhaps possible to visualize the results within the internal or external dashboard? The only things I now can visualize are: 
-	Jobs status 
-	Job frequent 
-	Job type 
-	Job observable classification 
I would rather like to visualize the results of the analyzers. I have both the internal as the external dashboard running.

**Comment by mlodic** [comment]
Results of analyzers are not something that can be visualized in the dashboard because you can't do decent statistics on unstructured data. Honestly it makes no sense in my opinion.

IntelOwl already has an integration with ElasticSearch. Please check the documentation about that and give it a try

**Comment by mrrobotnl** [comment]
Is there no other way to quickly look at what the results are? Not to be rude or anything but that was the whole promises of the framework? To have quickly insights of different API calls and what the results of those calls are?

**Comment by mlodic** [comment]
Honestly I did not understand what you mean for "results". In this thread you specifically asked for things in a dashboard but dashboards are for statistics.
Can you please specify clearly your use cases?

**Comment by mrrobotnl** [comment]
Hey Mldoic, thanks anyway for responding this quickly. The goal that I am working on is to get a functional Proof of Concept of this framework. 
The first part I already done with, there I looked at how can I install and configure this framework correctly. 
The second part of the research is: how can I make it easy for colleagues to access and read the data that is gathered with IntelOwl. And that is why I ask the question because for now people need to go to the Gui -> jobs -> select the correct job -> go to the right analyser -> unfold this result and go to report and then extract the data from the Json file. 
So, my question is: Is there an easier more automated way to extract the data without clicking trough the framework?

**Comment by mlodic** [comment]
Thank you for your response, we are interested in your use cases: it can be helpful to understand the direction of the project. I'll try to give you more info:
* Main purpose of IntelOwl is to extract data from several sources in the same place with a single request. Search and visualization features are lacking right now because they are not the main purpose of the framework. The framework was thought to be used once you find some digital forensic artifact and you need to understand more about it.  To do that you usually need to get live and actual data from several different sources: you do not need to check a database of old analysis because old data can be not accurate. It makes no sense in that use case to get old analysis because most of the times analysts needs to get fresh data: so they need to perform a new analysis. Once said that, I would like to understand which kind of jobs are you doing because this framework has been thought for security analysts in mind so your use case could be little different.
* Then we are about to release v5 major release that allows to create custom visualizations of the results to allow a better user experience from the GUI. I suggest you to check it out once we have it released. Advanced search features will be added too at a later moment (end of year)
* IntelOwl data is accessible via APIs too and we have dedicated clients (pyintelowl and go-intelowl) so you can do your own integrations and automation if you like and use your own flows and GUIs
