### ISSUE TITLE
[Analyzer] Recorded future

### ISSUE THREAD

**Issue by mrrobotnl** [intelowlproject/IntelOwl#1694]
## name
Recorded Future
## Link
https://www.recordedfuture.com/
## Type of analyzer
Domain, IP and URL 
## Why should we use it
Is a cool tool that gives back essential information about an domain, IP or URL. It gives risk scores with it. And it checks for vulnerabilities.
## Possible implementation
It does support API calls.

**Comment by mlodic** [comment]
is there free usage?

**Comment by mrrobotnl** [comment]
@mlodic , no currently not.

**Comment by mlodic** [comment]
IntelOwl has always tried to add (as a first priority) services which provides a free quota. This is because we want to add features that everyone can use, not only people who have the money to buy expensive products.

Plus, we would need a person who can test the integration and, without one with a subscription, this is impossible.

So I'll close the issue.
