### ISSUE TITLE
Oh snap! Auth broke

### ISSUE THREAD

**Issue by chavez243ca** [intelowlproject/IntelOwl#173]
Had IntelOwl up most of yesterday, couple accounts active, submitted a couple observations - all good. Had an admin do some minor hardening and rebooted the server, I went back in and did a docker-compose up -d - IntelOwl came back up, but no accounts able to login now including root.

Not sure what happened.

**Comment by mlodic** [comment]
Hi @chavez243ca, could you please provide more details?

Which IntelOwl release do you use? Did you upgrade IntelOwl during the maintenance?

Can you login with the admin in account in the Django Admin interface `http://<your_domain>/admin`?

If you can export the logs (should be here `/var/lib/docker/volumes/<project_folder_name>_generic_logs/_data`, I can check them and try to understand the issue

**Comment by chavez243ca** [comment]
Just built yesterday, so should be the latest version, no upgrade performed to my knowledge. Due to where that instance of IntelOwl resides compared to where I am typing this, exporting the logs is a bit of a challenge. However, I did grab a snippet of the django error log:

Traceback (most recent call last):

  File "./api_app/auth.py", line 66, in obtain_user_token

    code=status.HTTP_400_BAD_REQUEST,

rest_framework.exceptions.APIException: No such user exists or Incorrect credentials

2020-08-27 12:27:28 - api_app.auth - obtain_user_token - ERROR - obtain_user_token exception: No such user exists or Incorrect credentials

Also unable to access django admin with root creds

**Comment by mlodic** [comment]
That error is just a simple error that I think it is not be related to some bug in IntelOwl but just something wrong with your credentials.

A possible reason could be that you deleted the database when shutting down the application. How did you shut down Intel Owl? If you removed the volumes, all the users are gone.

I suggest you to create a new "superuser" like stated here https://intelowl.readthedocs.io/en/latest/Installation.html#after-deployment. Then login to the interface and check which users are currently active in the "Users" section.
If no other user is available, I think that my guess could be right. Otherwise, please let me know.

Just to clarify: 
`docker-compose down` -> shuts down the application
`docker-compose down -v` -> shuts down the application + remove all volumes (logs and database)

**Comment by chavez243ca** [comment]
My guess is the admin just rebooted the server w/o manually shutting down the containers. We do have a snapshot we might revert to, but I'd like to get to the bottom of this if I can.

**Comment by chavez243ca** [comment]
okay - reset the superuser and got in, all the created users from yesterday are missing.

**Comment by mlodic** [comment]
Ok, if it happens again please tell us. Have a nice day and enjoy the application 👍
