### ISSUE TITLE
DNStwist analyzer

### ISSUE THREAD

**Issue by Eshaan7** [intelowlproject/IntelOwl#188]
[dnstwist on GitHub](https://github.com/elceef/dnstwist).

It's available on PyPi and supports python3 so can be added in `requirements.txt` and used directly without subprocess.

**Comment by m0mosenpai** [comment]
Hi, I would like to work on this. Is there anything I should look out for that might help?

I'm also working on Issue #189 (thought I should mention this). Will give that priority as soon as I receive the API key.

**Comment by Eshaan7** [comment]
`dnstwist --format json domain.name` will be most normal scenario. On top of that, we should make available extra features as `additional_config_params` for `geoip`, `mxcheck`, `ssdeep`, `registered` - all these options are given in their docs.

@mlodic would be able to better explain the requirements.

**Comment by mlodic** [comment]
Yes, `json` output is mandatory to save the results easily in a dictionary.

Then I think that we should provide most of the available options:
* I would say that the `registered` option should be available as default, to avoid too many results in the output
* `geoip`, `mxcheck`, `ssdeep` all optionals
* `tld` as optional and setting the `abused_tlds.dict` dictionary as default

Also, the analyzer should support not only domains but URLs too

**Comment by m0mosenpai** [comment]
After looking at some already existing observable analyzers as reference, I'm a bit confused about some things:

1. I didn't quite understand on what basis are the key/ value pairs of `additional_config_params` decided and how to define a default value for them (example, in the case of `tld`)
2.  Just to be clear, since we can't use subprocess, we are importing and calling the functions directly based on available options?

Also, I hope it's okay if I ask some basic questions like these? Still trying to understand how everything works.

**Comment by mlodic** [comment]
Sure man feel free to ask :+1: 

1. I suggest you to see the (`dnsdb.py` analyzer of the `develop` branch)[https://github.com/intelowlproject/IntelOwl/blob/de6988af1e173044ef38ff698c912cb4e7d72b81/api_app/script_analyzers/observable_analyzers/dnsdb.py#L47]. You can set how many parameters you want in the configuration here with their defaults.
Then, when an analyzer is called, it is possible to customize those values by changing the values of this dictionary. If you see in the default [analyzer configuration](https://github.com/intelowlproject/IntelOwl/blob/de6988af1e173044ef38ff698c912cb4e7d72b81/configuration/analyzer_config.json#L149), if you call the `DNSDB` analyzer from the interface, it would add also the `server` and the `api_version` variables to customize the analysis.

1. I am afraid that the tool does not allow to be easily used as a library. I think that you could implement it with subprocess. Maybe @Eshaan7 could have more suggestions.

**Comment by m0mosenpai** [comment]
Oh, I see. I'm implementing it using subprocess for now, as I had trouble using the tool as a library as well. Let me know if there's an alternative you would prefer.

Also, according to the contributing docs, there needs to be a celery module added in [tasks.py](https://github.com/intelowlproject/IntelOwl/blob/master/intel_owl/tasks.py). But, tasks.py in master branch differs from the one in [develop](https://github.com/intelowlproject/IntelOwl/blob/develop/intel_owl/tasks.py) and since I'm working on develop, I'm not sure what I should change/add there.

**Comment by Eshaan7** [comment]
@m0mosenpai,

1. You may use subprocess. When I first looked at it, I thought it can be used via import directly but I see now that isn't the case. Sorry about the confusion.

2. Please refer to this URL (https://intelowl.readthedocs.io/en/develop/Contribute.html) for the contributing docs. We are a little late on the new release which is a major one and moves arounds a lot of code, hence the confusion. To be clear, you won't need to add a module to `tasks.py` anymore.

**Comment by mlodic** [comment]
Merged into `develop`: #243
