### ISSUE TITLE
PacketTotal API for .pcap files

### ISSUE THREAD

**Issue by Eshaan7** [intelowlproject/IntelOwl#189]
https://packettotal.com/api.html

**Comment by m0mosenpai** [comment]
Hi, I would like to try and work on this. Aside from the general contribution guidelines and docs, anything particular I should look out for that would be helpful?

**Comment by Eshaan7** [comment]
Hi, @m0mosenpai. Thanks for your interest, I've assigned this issue to you. Few things to note:

1. This would be a file analyzer with supported filetypes been mimetypes of `.pcap/.pcapng` files.
2. You could look under `api_app.script_analyzers.file_analyzers` and find many examples of file analyzers, that should really help you.
3. This analyzer would require an API key, so look at how this is enforced for other analyzers and follow same. You should sign up on packetTotal yourself and get an API key so you can test the service and code accordingly.
4. It seems like their API documentation is down for some reason, but you are in luck because they provide a [python SDK.](https://github.com/PacketTotal/PacketTotal-SDK) Do note that we do not want to add this SDK as a library, but you can go through it's [code](https://github.com/PacketTotal/PacketTotal-SDK/blob/master/packettotal_sdk/packettotal_api.py) and see how to make requests to their API, what params it needs, etc.

Feel free to ask here in case of any queries.

**Comment by m0mosenpai** [comment]
I went through their SDK and I noticed that they have more features as part of their API aside from just analyzing pcap files (like searching via pcaps, downloading pcap anaylsis archive etc.) (https://github.com/PacketTotal/PacketTotal-SDK/blob/master/packettotal_sdk/packettotal_api.py). Do I have to implement those features as well?

**Comment by mlodic** [comment]
Hi @m0mosenpai!

1. Well, the more you implement the better! :P Just always remember the main goal of IntelOwl: analyze an observable (IP address, domain, etc) or a file. So every API endpoint is useful if it can analyze at least one of those artifacts. 
For instance, the search API can be useful to look for IP addrs or domains and in that case it would be an "observable analyzer" instead of a "file analyzer".

2. You are right, at the moment there is no .pcap file available in that zip file. You could navigate in the [PacketTotal](https://packettotal.com) site, download one of the public .pcap that they made available and add it to the archive. If you can, try to get one with several hits so you have a stronger output while testing it manually.

**Comment by m0mosenpai** [comment]
I had another doubt...  in test_api.py (https://github.com/intelowlproject/IntelOwl/blob/master/tests/test_api.py#L72), do I have to create a similar function like this one for pcap files, since this one is for .exe ones? I'm assuming this file is for testing all the APIs that are used in analyzers.
Aside from this, I have written most of the code for the file analyzer. Waiting for PacketTotal to send me the API key so I can test everything out.

**Comment by mlodic** [comment]
:+1: perfect!

I think that for now it is not required to add that case to test_api.py...we are probably refactoring/adjusting that part of the testing suite (see #229) to make it more robust.

For your case, I think it is enough to add a new class here (https://github.com/intelowlproject/IntelOwl/blob/master/tests/test_files.py) that would manage all the analyzers that support .pcap files.

**Comment by m0mosenpai** [comment]
Uh about the API key, I still haven't received it despite multiple emails. Is it okay if I work on something else meanwhile? Or shall I just wait?

**Comment by mlodic** [comment]
Sure, feel free to work on something else. Meanwhile I asked a key too so in case they get me a key before you I could test your code.

**Comment by mlodic** [comment]
hey @m0mosenpai, have you received the API key? When you told us that you did not receive one, I requested one but I did not get anything back too. Well, that is quite strange 😅 

If you did not received anything, I'll close this issue

**Comment by m0mosenpai** [comment]
@mlodic Hi, I was about to ask you as well, what to do about this issue cause I didn't receive a key either. Their docs link also seems to be down and the support isn't responding to queries either.

**Comment by CITIZENDOT** [comment]
Same is the case with Recorded Future. I had requested demo 2 times. No reply from them yet.

**Comment by mlodic** [comment]
We can just skip these issues I guess.

In general vendors analyzers are less necessary in my opinion. This is an open source project that should support other open source projects first. So integrations with other sources/apps that are free to use should be a priority.
