### ISSUE TITLE
Remove python script.py to reduce dependencies

### ISSUE THREAD

**Issue by mlodic** [intelowlproject/IntelOwl#1899]
We should reduce the overall dependencies to install.
We should transform this script in a bash script for better compatibility.

We should take this refactor to solve [this issue](https://github.com/intelowlproject/IntelOwl/issues/1866) altogether

**Comment by Shud06** [comment]
we should do the following thing:

1. Use standard libraries: Whenever possible, use standard libraries instead of third-party libraries. This will reduce the number of dependencies that need to be installed.
2. Use lightweight libraries: If you do need to use a third-party library, choose a lightweight library that has few dependencies.
3. Bundle dependencies: If you have a number of dependencies, you can bundle them into a single package. This will make it easier to install and manage the dependencies.

and also Use bash syntax throughout the script
