### ISSUE TITLE
Error during Installation of 5.2.0 Version

### ISSUE THREAD

**Issue by akaheidy** [intelowlproject/IntelOwl#2008]
## What happened
While i was trying to install IntelOwl in my fresh new Ubuntu 2204 machine with docker and portainer installed it fails after trying to execute "sudo python3 start.py prod up" .
Here is the image
![image](https://github.com/intelowlproject/IntelOwl/assets/152916641/a54aab05-b1f3-425f-bd77-5655794622df)

Does anyone have an idea?
Thanks!

## Environment
1. OS: Ubuntu 22.04
2. IntelOwl version: 5.2.0

##  What did you expect to happen
IntelOwl being installed
## How to reproduce your issue
Trying to install in on a new machine
## Error messages and logs
ERROR: for celery_beat  Container "3c0ec9cf4418" is unhealthy.
ERROR: Encountered errors while bringing up the project.
Creating intelowl_celery_beat ...
Traceback (most recent call last):
  File "/opt/IntelOwl/start.py", line 345, in <module>
    start()
  File "/opt/IntelOwl/start.py", line 331, in start
    subprocess.run(command, env=env, check=True)
  File "/usr/lib/python3.10/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args, output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['docker-compose', '-p', 'intel_owl', '--project-directory', 'docker', '-f', 'docker/default.yml', '-f', 'docker/postgres.override.yml', '-f', 'docker/rabbitmq.override.yml', 'up', '-d']' returned non-zero exit status 1.

**Comment by mlodic** [comment]
hey, sorry but I have no idea, the logs that you sent are not enough to understand the problem on your machine.

resources of the machine? maybe you don't have enough resources there and while bringing up the project, the container were killed by the os

**Comment by akaheidy** [comment]
This machina has 2 core and 12 gb of RAM isn't it enough?
I want to mention also that I tried to unistall completely but nothing changed

**Comment by mlodic** [comment]
It should be good.

I managed to replicate the error. It seems it may happen for new cleaner installations only. The problem is that the containers go to the "unhealthy" status before having the chance to perform their initialization correctly.

There's a parameter in the Dockerfile which manages it. I have just changed in the `develop` branch from 40 seconds to 90 seconds to avoid this kind of problems.

I'll push a new release asap to fix the problem. Meanwhile you can use `test` instead of `prod` and checkout to the `develop` branch to get the fixed version before the release.

Thank you.

**Comment by akaheidy** [comment]
Hi, just tried in test mode and it works!
I will try it better to see if i see any other problems

Thank you <3
