### ISSUE TITLE
IntelOwl module With DFIR IRIS

### ISSUE THREAD

**Issue by keid2000** [intelowlproject/IntelOwl#2116]
Trying to integrate the IntelOwl module with IRIS.

But I get this error.
![ADSDADADADA](https://github.com/intelowlproject/IntelOwl/assets/159165053/19c50241-f7d4-4229-ab9e-95e51d0bf97d)

![DADASDAS](https://github.com/intelowlproject/IntelOwl/assets/159165053/81d06d40-e9d5-4084-bb7c-0f3be602f622)

**Comment by mlodic** [comment]
can you please tell us which version of `pyintelowl` are you running? and which version of IntelOwl are you using?

**Comment by keid2000** [comment]
I discovered I do not have pyintelowl.

But I downloaded it, and this is my version 4.4.5.

How can I know the version of IntelOwl?

**Comment by mlodic** [comment]
if you go to the homepage of the project, you'll have the version on the top left of the page. Have you just cloned and installed it?

I don't know if you can leverage or not pyintelowl in that integration but, if you can, that is the preferred method to integrate with IntelOwl

**Comment by mlodic** [comment]
ah I wasn't aware of that module.  I remember having talked with Iris' guys about an integration but nothing else.
So yes, I guess that the problem is about compatibility. We have made changes to IntelOwl that could have broken old custom client implementations.

I see that the specific module leverages `pyintelowl` internally (https://github.com/dfir-iris/iris-intelowl-module/blob/main/setup.py)
I have done some manual tests and I noticed the problem. I fixed the `pyintelowl` client and I just made a new version `4.4.6`. Considering that the Iris module leverages `pyintelowl>4.4.0`, I think you could just re-install that module and you would get the most recent version of pyintelowl together with it.
Please try and let me know

**Comment by keid2000** [comment]
Thanks for your effort and your manual test.

To make sure I understand, on the **IntelOWi** server, I do not need to update anything on it considering my version is 5.2.3.

What I need to do is re-install the modules that exist in IRIS that are reasonable for IntelOWi integration.

I will try it and let you know!
Thanks very much!

**Comment by keid2000** [comment]
That is happen when I try to re-install the module:

![image](https://github.com/intelowlproject/IntelOwl/assets/159165053/7fd5eb70-0fb2-46f9-a101-aca4f2cd5424)

**Comment by keid2000** [comment]
I figure out the problem, when I run the buildnpush2iris.sh, this line in resolve.conf file get removed which lead to disable the internet connection.

![8888](https://github.com/intelowlproject/IntelOwl/assets/159165053/ab13c9a8-52ab-4973-b120-b561a2e3c17d)

But I did not figure the solution yet.

**Comment by keid2000** [comment]
It solve the first error, but we have a new one right now:

![erroe2](https://github.com/intelowlproject/IntelOwl/assets/159165053/6329fdaa-69ed-4ed1-b161-a2fdeaba0d85)

Do I have to configure all analyzers on Intel Owl?

**Comment by mlodic** [comment]
Ok I think I got the second problem (they are all related to the fact the IntelOwl server changed over time with major releases which can break old integrations but this iris module hasn't been updated as a consequence)

Once upon a time, if the client did not set any analyzer, IntelOwl would have executed _all_ the available ones by default.
This does not happen anymore, hence the problem you discovered.
Why? That's because we have a new concept with is called "Playbook" : basically they are a set of preconfigured analyzers. This is the preferred method now to integrate with IntelOwl.
To make this change we would need to make a patch to the IRIS module to have it use this new feature and leverage the default Playbook called "FREE_TO_USE_ANALYZERS" at least.
I'll make a patch for the main repository but then you'll have to wait for them to merge it. Once I have done it, I'll link here the PR. Please add a comment to let them know that you need this so they may solve the problem earlier.

**Comment by mlodic** [comment]
I think this could work once merged: https://github.com/dfir-iris/iris-intelowl-module/pull/1/files

**Comment by keid2000** [comment]
Thanks for your clarification.

I will add a comment in their repository.

and I will try the **intelowl_handler.py** until the patch to the IRIS module is finished.

**Comment by keid2000** [comment]
I love you. It works when I apply the last changes!
![image](https://github.com/intelowlproject/IntelOwl/assets/159165053/9a5df9ba-173b-4964-8591-2dc7c016c6a4)

**Comment by mlodic** [comment]
cool! 

If you want to use IntelOwl even more deeper (for example analyze the ioc in different ways, with other playbooks), there's room to make additional changes to that module and allow to specify which playbook to leverage (in that way it would emaulate the "Scan" page behavior in IntelOwl)

**Comment by CyberAbwehr** [comment]
Please can you add playbooks as a value like

Main  IntelOwl URL  http://192.168.1.44  True
Main  IntelOwl API key  ***************  True
Main  IntelOwl playbook FREE_TO_USE_ANALYZERS True

so that we can use every playbook that we have configured in IntelOWL.

**Comment by keid2000** [comment]
Where I can find this room?

**Comment by keid2000** [comment]
> cool!
> 
> If you want to use IntelOwl even more deeper (for example analyze the ioc in different ways, with other playbooks), there's room to make additional changes to that module and allow to specify which playbook to leverage (in that way it would emaulate the "Scan" page behavior in IntelOwl)

Where I can find this room?

**Comment by mlodic** [comment]
meanwhile closing this as problem solved. Additional integrations with Iris should be opened directly on the IRIS github projects

**Comment by mtridici** [comment]
Hi, I'm experiencing a similar error trying to integrate DFIR-IRIS 2.4.24 with IntelOwl 6.4.0. DFIR is a really great tool, I love it, but if I can't add any additional info using the available modules I will have to choose another tool. But i don't want to do it. It is simply the most complete open source tool. Please, take care of these modules and make them working and up to date. I tried to fix this problem in several ways, but I'm not able to solve the issue.

**Comment by tkolaski** [comment]
Same problem,
IntelOwl 6.5.1 -
 iris [IRIS v2.4.27](https://github.com/dfir-iris/iris-web)

400 Client Error: Bad Request for url: http://10.10.4.136/api/analyze_observable. Details: {'errors': {'detail': ['No Analyzers and Connectors can be run after filtering:\n']}}. Details: None
Encountered error processing hook on_manual_trigger_ioc
