### ISSUE TITLE
Bug Yeti Connector is not working

### ISSUE THREAD

**Issue by CyberAbwehr** [intelowlproject/IntelOwl#2120]
## What happened
IntelOWL: v5.2.3
YETI: 2.1.3

**Cant send observable to yeti**
Error: "404 Client Error: Not Found for url: http://192.168.1.45/api/v2/observable/"

**YETI API:**
http://192.168.1.45/api/v2/observables/

###!!! observable[s] !!!###

**Hardcoded in IntelOWL:**
yeti.py
url = f"{self._url_key_name}/observable/"

## Environment
1. OS: Ubuntu 22.04 LTS
2. IntelOwl version: v5.2.3
3. YETI: 2.1.3

##  What did you expect to happen
Write IOCs to Yeti

## Error messages and logs
Error: "404 Client Error: Not Found for url: http://192.168.1.45/api/v2/observable/"

**Comment by mlodic** [comment]
hey, thanks for reporting. The YETI connector hasn't been touched since 2021 and I know that this year YETI has just released a new major release. This could mean that our connector could not support this new major version.

If you have both IntelOwl and YETI in place in your environment, you could help us fixing this problem with some lines of python code.
This is [where you can touch the integration ](https://github.com/intelowlproject/IntelOwl/blob/master/api_app/connectors_manager/connectors/yeti.py). I think that maybe just few little things are required to be changed. I don't see many information in their [official docs here ](https://yeti-platform.io/docs/api/) though

**Comment by CyberAbwehr** [comment]
Yes I cloud help you. ;-)

Best regards

Matteo Lodi ***@***.***> schrieb am Do. 8. Feb. 2024 um 17:38:

**Comment by mlodic** [comment]
superseded by https://github.com/intelowlproject/IntelOwl/issues/2309
