### ISSUE TITLE
New analyzer: emailrep.io + "generic" classification

### ISSUE THREAD

**Issue by theguly** [intelowlproject/IntelOwl#281]
hi there, i was about to starting an integration with emailrep.io when i found that observable classification doesn't let me to query for an email object.

maybe you're not interested in doing query against email address?

in case you are, do you think you could add that classification to js definition (i'm reluctant to dig into docker build script and minimized javascript, if possible...)?

thanks

**Comment by mlodic** [comment]
You are right, ATM IntelOwl does not support emails as observables...there are already existing integrations that would benefit of this change (ZoomEye,...) but it is not yet supported. 

This is a recurrent request (analyze new types of observables) so I think that it is time to understand how to manage this new possible feature. 

I'd like to mention @Eshaan7 because we already talked about this. It would be nice if the Angular Interface would dynamically support new types of observables when we add new ones. Server side I guess we can just add new ones without particular problems. Also I do not think that PyIntelOwl client would be affected in any case too. Thoughts?

**Comment by Eshaan7** [comment]
Don't really think the dynamic way would work although adding a new observable type on the angular client would take little effort. Same goes for pyintelowl. For both clients, we just need to add an entry for new the observable type and it's corresponding regular expression.

But as discussed before, I think we should add a new observable type called `generic` which would be a placeholder for observable types like email, city, phone number, location, etc. Basically, only certain analyzers allow any kind of observable so if user chose `generic` as the type, we just pass the value to the analyzer and see what happens.

@theguly so I suggest you to add `generic` to the `observables_supported` parameter. Soon, we will add support for the same.

**Comment by mlodic** [comment]
Yes, in this way we would have the chance to analyze *everything* and we won't have to think about it again.

My only concern is one. For instance, one analyzer would like to change its behavior based on the observable classification (ex: emails and phone number use different endpoints): that specific analyzer would have to perform the "classification" of what kind of observable arrived on its own, while IntelOwl could have already done it automatically. At the moment, this is an edge case so I guess we can ignore my concern and go on like you proposed.

**Comment by theguly** [comment]
ok i have my side done, waiting for generic classification to be available to submit a PR

thanks

**Comment by mlodic** [comment]
I just added support for "generic" type of observables in the `develop` branch of `pyintelowl`. Please @theguly push your code/PR as a draft so we can start to test it with pyintelowl
