### ISSUE TITLE
URLscan API

### ISSUE THREAD

**Issue by amanjiofficial** [intelowlproject/IntelOwl#36]
We should add an analyzer to extract info from URLscan

https://urlscan.io/about-api/

Suggestions Please @mlodic.

**Comment by mlodic** [comment]
Yes, that would be great. We should give the chance to search for an available analysis.

Also, the user should have the chance to decide in advance, in case the search does not give any result, if he wants to submit the URL for an active analysis. This is important because that would require additional time and not everyone wants to wait.

**Comment by heipei** [comment]
Let me know if you have any questions around using the API. We recently revamped the API documentation and it now includes information about quotas and rate-limits.

**Comment by mlodic** [comment]
Thank you @heipei, I will contact you if we have any problems! We will try to add this analyzer as soon as we can, but we are pretty busy this month with other tasks. 

The addition of this analyzer should be pretty easy and straightforward also for new contributors, so I strongly invite everyone reading this to jump into the docs and try to make a pull request.

**Comment by RamnathKumar181** [comment]
Sorry about the delay, had a few college deadlines. Will get back at this asap!

**Comment by RamnathKumar181** [comment]
Hey @Eshaan7 @mlodic , 
I have a few updates and thought it would be pointing a few troubles I had:
1> Currently, there is a new release of black package (20.8b1) whereas, the one running on docker is 19.10b0. We might want to specify this explicitly in the docs so that others could install the right version and not face any errors in the travis build.
2> In the contribution page(https://intelowl.readthedocs.io/en/latest/Contribute.html), the command `$ docker-compose -f docker-compose-for-tests.yml up `` is wrong (there is a '`' in the code). 
3> I am having trouble importing the secret files and running the tests locally. Is there a doc for this?
Again, thank you for your time, and sorry for the delay!

**Comment by Eshaan7** [comment]
1 & 2) Thankyou for pointing these out. Will make the changes in the docs soon.
3) Can you provide a log/screenshot of the error you are facing ? ([docs](https://intelowl.readthedocs.io/en/latest/Contribute.html#pass-linting-and-tests) on running tests locally).

**Comment by RamnathKumar181** [comment]
Hey @Eshaan7 @mlodic ,
1> The submit_task passes on url such as "youtube.com", "www.google.com", etc. It fails on the test case "https://www.google.com/search?test" under the error code 400, bad request. The message on their site is: "The submitted domain is on our blacklist. For your own safety we did not perform this scan..." (https://urlscan.io/). How do we pass the travis build if this site is blacklisted?
2> How do I run on the utils test? I am trying the code `docker exec -ti intel_owl_uwsgi python manage.py test tests.utils.<class_name>.<func_name>`. This leads to the below error. 
`Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    main()
  File "manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/commands/test.py", line 23, in run_from_argv
    super().run_from_argv(argv)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/commands/test.py", line 53, in handle
    failures = test_runner.run_tests(test_labels)
  File "/usr/local/lib/python3.7/site-packages/django/test/runner.py", line 627, in run_tests
    suite = self.build_suite(test_labels, extra_tests)
  File "/usr/local/lib/python3.7/site-packages/django/test/runner.py", line 488, in build_suite
    tests = self.test_loader.loadTestsFromName(label)
  File "/usr/local/lib/python3.7/unittest/loader.py", line 205, in loadTestsFromName
    test = obj()
TypeError: test_pulsevide() missing 1 required positional argument: 'self'
`
Any other simpler way to run only this test?
Anyways, I ran the entire test folder, and the search option passed. Was just wondering why this error is thrown.

**Comment by Eshaan7** [comment]
I think what you want to do is: `docker exec -ti intel_owl_uwsgi python manage.py test tests.test_observables.URLAnalyzersTests.test_urlscan_search`

**Comment by heipei** [comment]
You could use any other URL (e.g. the IntelOwl Github URL) for scanning. Google is blacklisted for specific reasons, as is Youtube.

**Comment by RamnathKumar181** [comment]
Thank you very much @heipei . It worked! All the tests passed on my local system!
@Eshaan7 , there were some complications while pushing the code. I had to create a new PR since the previous repo apparently didn't exist. Sorry about that. I Will work on any further complications in the tests asap.
Thank you for your time!

**Comment by RamnathKumar181** [comment]
Hey @Eshaan7 , Is there an issue raised to make the relevant changes to the contribution page? I would be glad to help out with that, if possible.

**Comment by Eshaan7** [comment]
> Is there an issue raised to make the relevant changes to the contribution page

Not really. The changes I made were few styling changes and some fixes to make urlscan's analyzer easier to test.
