### ISSUE TITLE
Migrate to Django 3.2

### ISSUE THREAD

**Issue by mlodic** [intelowlproject/IntelOwl#379]
When the new Django LTS is available, we should try to move the project to that release + understand if Django 3 provides useful features that we could implement into IntelOwl.

(At the moment we are in the current LTS (2.2.x).

This release is planned to be shipped on April (https://docs.djangoproject.com/en/3.2/releases/3.2/)

It is particularly important to go through the new features and the deprecated/removed ones to bring to the project the most recent technologies.

**Comment by palrohitg** [comment]
@mlodic  can I work upon this issue shifting from 2.2.x to 3.2?

**Comment by mlodic** [comment]
sure

**Comment by mlodic** [comment]
https://twitter.com/djangoproject/status/1379372684400861185 The LTS version is finally available

**Comment by Eshaan7** [comment]
For upgrading to django 3.2, we'd need to drop `eventlet` (reference: https://github.com/celery/celery/issues/5924).

I see three resolutions:
- Since django 2.2 LTS is supported until April 2022 and if we don't stand to benefit a lot from the the upgrades, we can just keep eventlet and django 2.2.
- Drop eventlet and upgrade to django 3.2.
- We can _try_ to use `gevent` but that also has it's own complications. 

On using IntelOwl internally, we at Certego have noticed eventlet causing a number of other issues as well. So it might just be time to drop it.

**Comment by mlodic** [comment]
I agree, we could just move with the 2nd option in my opinion
