### ISSUE TITLE
Add support for Kubernetes deployments

### ISSUE THREAD

**Issue by mwatermolen** [intelowlproject/IntelOwl#443]
Hey all,

I have been using intel owl in kuberntes for a few weeks now, However the process to get it setup is quite painful. Given the enterprise interest, is there is any planned official support for Kubernetes deployments? If not, I think that would be a next to invaluable addition for easy deployments!

Keep up the great work
Max

**Comment by mlodic** [comment]
Hey @mwatermolen, thank you for your interest in the project!

Honestly we did not work on Kubernetes. On the contrary, I was planning to provide support for Docker swarm for scalable deployments. This is because IntelOwl is based on docker and that seems faster and easier to support.

Could you please share with us your experience, your problems and everything else that could useful for other people with the same problem and for us to help you?

Plus, in the documentation you can find a link to an old post from a guy that deployed IntelOwl in GKE. Maybe this could help: https://intelowl.readthedocs.io/en/latest/Advanced-Usage.html#google-kubernetes-engine-deployment

**Comment by mwatermolen** [comment]
Howdy @mlodic, 

So on the topic of Docker swarm, the biggest hassle of intelowl on Kuberntes is the image building. If the images are built and published by the intelowl team it will make the Kuberntes/Swarm ops 10x easier 🚀. 

 Beyond that a helm chart could be built with low-moderate effort. Right now I am using just yaml based on that post for GKE , but when I redo it here soon I will package it as a helm chart. If I get around to it I will post the helm chart, but official docker images would be the dream 🤣

**Comment by mlodic** [comment]
won't do
