### ISSUE TITLE
FireHOL blocklists analyzer

### ISSUE THREAD

**Issue by mlodic** [intelowlproject/IntelOwl#53]
http://iplists.firehol.org/

We could integrate an analyzer for the FireHOL blocklists. In this way, we could check if a specific IP was reported as malicious by one of those lists.

We should manage the download of these lists internally in the project. Then we should update these lists regularly to allow the IntelOwl users to get fresh results.

**Comment by subhashissuara** [comment]
Hello there, I would like to work on this issue. 
[firehol_level1](http://iplists.firehol.org/) mentions `This IP list is a composition of other IP lists.` so, do we need to check from this list and maintain it? or am I missing something? (Since you mentioned, `We should manage the download of these lists internally in the project.`) Thank you

**Comment by sp35** [comment]
Hi @subhashissuara you can store it as a text file the media root directory.
A very similar analyzer is [Tor Analyzer](https://github.com/intelowlproject/IntelOwl/blob/master/api_app/script_analyzers/observable_analyzers/tor.py)

**Comment by mlodic** [comment]
solved with #417
