### ISSUE TITLE
Missing configuration for `VirusTotalv3ScanFile` Analyzer in `analyzer_config.json`

### ISSUE THREAD

**Issue by m0mosenpai** [intelowlproject/IntelOwl#535]
https://github.com/intelowlproject/IntelOwl/blob/master/api_app/script_analyzers/file_analyzers/vt3_scan.py
No config seems to have this analyzer as it's `python_module`.

**Comment by sp35** [comment]
AFAIR, this is not a bug, you are right this module is not directly associated to an analyzer but indirectly this module is called when the file needs to be uploaded too, inside the single module for Virustotal, using different config params.

**Comment by Eshaan7** [comment]
@mlodic can you comment your thoughts on this? While wait @sp35 said is true it still doesn't why we do not have a configuration for this particular module.

**Comment by mlodic** [comment]
how the VT analyzers are managed is kind of tricky because they call each other and are pretty complicated. Maybe they need some rework now.

Anyway, this is because most of the times it is useless to upload a file for analysis directly.
VT provides the option to do it without other previous requests but:
* if it was already uploaded, the analysis is already available in VT and we would perform a useless upload
* If we want to re-do the analysis because outdated, we would like to leverage the `rescan` option that does not need the upload of the sample

So, most of the times, a `get` request should be performed to see if the sample is already there in VT or not before uploading it without having performed any checks. This would avoid a lot of useless sample uploads.

All this logic is already implemented in those analyzers.

Plus, I guess I removed the configuration of that specific one once I noticed that executing `run_all_analyzers` would waste a lot of VT quota without reasons because the scan feature was already in the workflow of the `get` analyzers, causing the same tasks to be requested multiple times.

(there were also other problems, for example [here](https://github.com/intelowlproject/IntelOwl/issues/299))
