### ISSUE TITLE
Running IntelOwl on localhost?

### ISSUE THREAD

**Issue by SammyTheBEAST** [intelowlproject/IntelOwl#635]
Hello,

For security reasons, I only want to access IntelOwl through a VPN connection. Normally, I just change the IP addresses to point to 127.0.0.1 and that works. I've changed the IP addresses in the intel_owl.ini, entrypoint_uwsgi.sh, and the nginx.conf files to be on the localhost 127.0.0.1, but I'm getting HTTP 0 errors with barely any way to debug it. What do I need to do to get IntelOwl to only be accessible on the localhost?

Thank you

**Comment by mlodic** [comment]
Hi,

I don't know how much you know about Docker, but the application server (uwsgi) is executed in the docker network. This means that if you changed the `0.0.0.0` values that you found with `127.0.0.1` that would break the application because the nginx container would not be able anymore to connect to the uwsgi one. The uwsgi container would be reachable only by itself.
The `0.0.0.0` means that the uwsgi container is reachable to all the containers in the docker network, not that is reachable by everyone in your host network.

By default, you should just run IntelOwl as stated in the docs and it would expose the application to the port 80 from your host machine. Then, you need to set up your own network to allow that port and that machine to be reachable by the point where you want to use the application. And this is out of scope of IntelOwl.

So, there is no need to apply any change to the configuration or code. You would just need to work with firewall rules and other network configurations to have everything work properly.
