### ISSUE TITLE
Capa v3 update

### ISSUE THREAD

**Issue by mlodic** [intelowlproject/IntelOwl#708]
https://www.fireeye.com/blog/threat-research/2021/09/elfant-in-the-room-capa-v3.html

**Comment by Yshaq** [comment]
Hey, I'd like to pick up this issue.

Installing capa directly from pip won't work because that doesn't set up the default library identification signatures. This way, we would have to somehow download the sigs folder from the [capa repo](https://github.com/mandiant/capa) and also modify the capa command being run.

What I'm thinking of doing is cloning the capa repo, and then [installing capa with pip from the local source](https://github.com/mandiant/capa/blob/master/doc/installation.md#method-3-inspecting-the-capa-source-code). This way the sigs are installed and the current command running need not be modified. Shall I go ahead with this method?

**Comment by mlodic** [comment]
Yes, remember that it is important to bring proof of a successful result so we can clearly understand that this method works! Thanks!

**Comment by mlodic** [comment]
done with v3.3.0
