### ISSUE TITLE
[New analyzer] Integrate new FileScan service

### ISSUE THREAD

**Issue by mlodic** [intelowlproject/IntelOwl#709]
https://filescan.io/api/docs

**Comment by fear-the-reaper** [comment]
Quick question: Do I need to integrate all of the endpoints?

**Comment by mlodic** [comment]
No, you would need to leverage the endpoints required to check:
* if the file you are about to analyze is already available in the service
* if not, send the file to the service for analysis
* poll for results 

This is a logic that we have already implemented in a lot of other analyzers (`triage`, `dragonfly`, `intezer`, `cuckoo`, etc) so I'd suggest to check them as an example

**Comment by uzair-ali10** [comment]
Hey, i would like to take this up
Please assign it to me

**Comment by eshaan7** [comment]
On further reading through [FileScan API docs](https://www.filescan.io/api/docs), I see that we can make 2 analyzers out of filescan. One for Observable analysis and other for File analysis.

- [ ] `FileScan_Upload_File`. Fixed by https://github.com/intelowlproject/IntelOwl/pull/781.
- [ ] `FileScan_Observable`.


The observable analyzer will use the [`/api/reports/search`](https://www.filescan.io/api/docs#/reports/search_report_api_reports_search_get) endpoint. 

Tip: Open your browser's network tab and make some queries in the searchbar given on their [homepage](https://www.filescan.io/scan) to see how this endpoint works.
