### ISSUE TITLE
New Playbook: run only "free" analyzers

### ISSUE THREAD

**Issue by eshaan7** [intelowlproject/IntelOwl#733]
*updated: 15th March 2022*

## Idea / Motivation

> An option that allows the user to only run free analyzers, the ones that don't require API Keys or login/password.

The main use-case for this is the following example:
- A user has configured some paid analyzers (with keys/credentials) but maybe for some analysis they want to save on API/service credits by checking the "run only free analyzers" option.

## Pre-requisite(s)

- [ ] #628

## Implementation Idea

This can be solved by creating a playbook that contains all the free (without api key/login) analyzers.

**Comment by 0x0elliot** [comment]
Can I take this issue up? From the looks of it, I might need to add minor changes to the backend and IntelOwl-ng (And probably PyIntelOwl)

Any guidance before I proceed?

**Comment by mlodic** [comment]
yep you are right, this involves all the projects.

I would suggest starting from the backend then the python client and lastly the frontend.

This would probably be another flag the application should receive once it receives analysis requests from the user. (https://github.com/intelowlproject/IntelOwl/blob/master/api_app/api.py#L36)

**Comment by mlodic** [comment]
I think it makes sense.

There is a [serializer](https://github.com/intelowlproject/IntelOwl/blob/master/api_app/analyzers_manager/serializers.py#L32) which manages the data extracted from that JSON file.

**Comment by 0x0elliot** [comment]
Thanks! Looking into this.

**Comment by 0x0elliot** [comment]
Hey @mlodic! I forgot to update you on this back then. I reached out to @eshaan7 separately regarding this issue when I was assigned to it and we came to the conclusion that marking the analyzers as "free" might have been a hassle and some more discussion was needed to be done on moving forward with keeping this feature in mind.

I would appreciate it if we can continue that discussion and see how we should proceed with solving this problem.

One of the solutions that I propose to solve this is that we can add a new option key to <code>analyzer_config.json</code> called "subscription_type" and have its value by default if nothing is provided for an analyzer as a free like the <a href = "https://github.com/intelowlproject/IntelOwl/blob/5cee175e48dd607efb34ba013e4001798dc432e7/api_app/analyzers_manager/serializers.py#L48">docker based</a> option.

But I need confirmation on this if we can even move forward with this because there is some clarification needed to confirm if all our analyzers do actually have a free version that we have adapted them for. If not then it seems like we would need to go through them one by one which seems to be the part that would cause the hassle. 

How should I proceed with this one? What do you folks say?

**Comment by mlodic** [comment]
I think that, in some way, this problem could also be solved by the "Playbook" feature #628 (we could pre-load a pre-configured playbook with only the free-analyzers) but that would certainly require more work to solve it.
Meanwhile, we could solve it the easier way we mentioned.

I think that every analyzer which needs an API key/login should not be considered as "free", while all the other yes.
I don't think it is too slow to go through all of them: it would be enough to check the type of configuration they already need and, based on that, understand if they are free or not.

**Comment by devmrfitz** [comment]
@0x0elliot Are you working on this?

If not, @mlodic do you recommend me to work on this issue?

**Comment by mlodic** [comment]
you can, but it would require you to work from the branch `dev-v4` where there is the new GUI based on React

**Comment by 0x0elliot** [comment]
> @0x0elliot Are you working on this?
> 
> If not, @mlodic do you recommend me to work on this issue?

I am not working on it. You can take care of this.

**Comment by mlodic** [comment]
will be solved by #628

**Comment by mlodic** [comment]
closed with #1238
