### ISSUE TITLE
some analyzer are missing the monkeypatch and so the tests

### ISSUE THREAD

**Issue by mlodic** [intelowlproject/IntelOwl#840]
- [ ] https://github.com/intelowlproject/IntelOwl/blob/master/api_app/analyzers_manager/observable_analyzers/cymru.py
- [x] https://github.com/intelowlproject/IntelOwl/blob/master/api_app/analyzers_manager/observable_analyzers/mb_google.py
- [x] https://github.com/intelowlproject/IntelOwl/blob/master/api_app/analyzers_manager/observable_analyzers/tor.py
- [x] some docker-based analyzers like Thug
- [ ] others?

@eshaan7 do you think there is a reason for that or they just miss?

**Comment by eshaan7** [comment]
1. Did not specify monkeypatch in `cymru` and `tor` because I thought we wanted to _actually_ check that the tor downloader works. But yeah we can add them.
2. The monkeypatch in `mb_google` comes from `mb_get` via class inheritance.
3. The monkeypatches are not defined individually in docker based analyzers instead it is defined only once in the `DockerBasedAnalyzer` base class.

**Comment by mlodic** [comment]
thanks for the explanation. I think that we can consider tor and cymru like the others and mock them. I'll keep the issue open so.

**Comment by fear-the-reaper** [comment]
@eshaan7 and @mlodic can you tell me what I need to do in order to do this task since I'm not familiar with monkey patch and all. Thank you!
