### ISSUE TITLE
Unable to Create Superuser on Fresh Install. Can't login initially 

### ISSUE THREAD

**Issue by r-whitt** [intelowlproject/IntelOwl#852]
Forgive me if this has been covered somewhere else. I am new to IntelOwl. I tried to follow the IntelOwl's docs <https://intelowl.readthedocs.io/en/latest/Installation.html#users-creation> and I also watched the linked YouTube video <https://www.youtube.com/watch?v=GuEhqQJSQAs>.

I appreciate everybody's help with this! Please let me know if you need anything else and I will be happy to get it for you.

**Issue**: 
I cannot create a superuser by running <sudo docker exec -ti intelowl_uwsgi python3 manage.py createsuperuser> after a fresh install. I can access the Webpage, I just cannot login initially. 

**Goal of this Incident:** 
Get some guidance to resolve this issue so I can get past the initial setup to use IntelOwl.

**Versions**: 
Docker version = 20.10.7
Docker-compose version = 1.27.4 (had to follow these <https://stackoverflow.com/questions/57456212/error-version-in-docker-compose-yml-is-unsupported> steps to upgrade to 1.27.4 as Ubuntu 20.04.2 only supports 1.25 initially and 
Ubuntu Version = 20.04.2
Attached is the output containing the errors

**Background/Steps:** 
- I installed a fresh Ubuntu 20.04 build via VMWare & made sure it was up to date. 
- I followed IntelOwl's Installation Docs (not just the TL;DR) & wanted the video they linked (exact links at the top).
- Installed Docker, Docker-Compse, & Python 3
- I had to upgrade docker-compose to fix an error stating version not specified
- When I start IntelOwl command: "sudo python3 start.py prod up", I see 2 big errors that I can't seem to fix despite research (Cannot connect to amq;...@rabbitmq:5672, Errno 111, connection refused && password authentication failed for user "user". 
-- I triple checked the username & passwords match in env_file_app & env_file_postgres. 
-- I have researched, but I haven't found anything that relates. 
-- See attached "IntelOwl_Start_Output.txt" for exact Output & errors
[IntelOwl_Start_Output.txt](https://github.com/intelowlproject/IntelOwl/files/7884443/IntelOwl_Start_Output.txt)
-At this point, I can log into the Web Portal @ 127.0.0.1
- Now, I try to create a superuser so I can log into Intel Owl. I ran <sudo docker exec -ti intelowl_uwsgi python3 manage.py createsuperuser>. However, I only get errors about invalid password for db user "user". See attached "Create_Superuser_Output.txt for the exact command & output. 
[Create_Superuser_Output.txt](https://github.com/intelowlproject/IntelOwl/files/7884459/Create_Superuser_Output.txt)

**Comment by mlodic** [comment]
hey @r-whitt , thanks for reporting this and for your interest in IntelOwl. Your report is extremely useful for debugging the issue.

* are you sure that `POSTGRES_PASSWORD` in `docker/env_file_postgres` and `DB_PASSWORD` in `docker/env_file_app` are the same?
* in the logs you sent me, it was not the first time that you have run IntelOwl because the DB was already initialized. Is it possible that you first ran IntelOwl, then changed the values in the environment files and then ran it again?
* `Cannot connect to amq;` errors are ok if they stop. (that worker is waiting for the broker to come up. All normal)
* you cannot create the superuser as a consequence of the fact that the application was not able to connect to the DB correctly.

I would suggest to perform a cleanup by running `sudo python3 start.py prod down -v` (this would remove all the docker volumes, so the DB too) and then re-run the application from scratch.

**Comment by r-whitt** [comment]
Hey @mlodic, 
You're a genius! Apparently, I did either initially mess up my password or change it after. Cleaning it up using your command worked. 

Thank you again. I really appreciate your quick reply and help. 

Have a good day!
