### ISSUE TITLE
Refactor: move analyzer/connectors classes attributes initialization from set_params to __init__

### ISSUE THREAD

**Issue by mlodic** [intelowlproject/IntelOwl#926]

**Comment by eshaan7** [comment]
What is the motivation behind this change ?

**Comment by eshaan7** [comment]
> I don't get why we run `set_params` inside the `__post__init`.

Again, this is just to allow extensibility and maintainability. One is allowed to overwrite `set_params` and `__post__init` methods in the child classes but never `__init__`.

> instead of just extending the __init__ in each IntelOwl analyzer.

If we allow extension of `__init__`, then child class need to have a call to `super().__init__` passing the appropriate arguments in the right order. This is much more error-prone and makes it difficult to change or add new arguments to `__init__` in the future. The point of `set_params` is to abstract away this complexity from the child classes because the people writing the analyzer/connector integrations do not need to be concerned with the inner workings of the `Plugin` class.

> I am annoyed by the linter telling me that we should not initialize parameters there

We can just disable/ignore that rule for the particular line.

**Comment by mlodic** [comment]
ok from this point of view it makes sense the sacrifice. It is also important to keep this consideration here as historical. thanks
