### ISSUE TITLE
Discussion: Env files should have .env extension

### ISSUE THREAD

**Issue by Andrew-Chen-Wang** [intelowlproject/IntelOwl#97]
Some IDEs like having .env files because their extensions can easily digest those and show syntax errors. Additionally, it's just habit/conventional to have these "." files that are either unnecessary or "secretive" stay as . so that gitignore files can have something like:

```
.*
!.travis.yml
etc.
```

**Comment by Eshaan7** [comment]
We have followed the `.` prefix convention for files that are not of concern to the end-user (for example, `.env`, `.travis.yml`, etc.) but the reason we did not prefix each env file with a `.` is because env files especially `env_file_app` are the heart of this project - we want the users to completely configure the env files. For example, inputting the different API keys because w/o them this application is just 10% as powerful as it can be.

**Comment by Andrew-Chen-Wang** [comment]
Ah I see; couldn't really understand why it was like that to begin with. I was just thinking something like app_template.env could be useful since it 1. still carries the keyword `env` and 2. is stated as a template so that the user knows this shouldn't be public. (Especially if you use something like secrets manager or parameter store with ECS, then you don't need to do your little function that grabs secrets from ssm at a pretty hefty cost).

**Comment by Eshaan7** [comment]
On another thought, we could convert `env_file_app_template` into a INI file that can then be parsed using python's [configparser] (https://docs.python.org/3.6/library/configparser.html). As mentioned in their docs, "You can use this to write Python programs which can be customized by end users easily." - it fits best for our use case and is a pythonic approach.
